### ISSUE TITLE
Public keys really are public

### ISSUE THREAD

**Issue by sarneaud** [SalusaSecondus/CryptoGotchas#20]
Hi, nice collection of gotchas.  Here's another suggestion:

An Australian government org created a cryptosystem called PLAID that tried to treat RSA public keys like secret IDs.  RSA doesn't guarantee secrecy of public keys, and figuring out the public key from messages is an example of the German Tank Problem: https://eprint.iacr.org/2014/728.pdf (That whole doc is a good read for analysis of real-world cryptosystems.)

Just a neat example of "Only rely on what your primitives explicitly promise."

Actually, you could do a whole section on misuses of RSA :/

**Comment by SalusaSecondus** [comment]
Thanks. I'll definitely take a look at that.

One interesting thing is that RSA keys really *can* be used in a reversed method safely. Assuming that you *randomly generate your `e` value* then deriving `e` from `d` and `N` is just as hard as the standard problem of deriving `d` from `e` and `N` (or equivalently factoring `N` in either case).
