### ISSUE TITLE
Wrote "an" as "and"

### ISSUE THREAD

**Issue by danegraphics** [SalusaSecondus/CryptoGotchas#5]
> If an adversary can get you to use an arbitrary algorithm, then they can select **and** insecure or completely broken one.

**Comment by danegraphics** [comment]
There are some other writing errors like this. I just recommend some editing look overs. Another weird thing was "it data" (just use the find function to read the sentence).

**Comment by SalusaSecondus** [comment]
Thank you. I shook out most of the bad ones but haven't gone over it with fine-toothed comb yet.
